// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzxuaqraifxudedrtkij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6eHVhcXJhaWZ4dWRlZHJ0a2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NTU5ODMsImV4cCI6MjA1MDUzMTk4M30.2W7Vlg3gd9iZuufCpIilEo0Kq2fZUFnqe57dF5BjHsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);